--- #YAML:1.0
name:                Net-PubSubHubbub-Publisher
version:             0.90
abstract:            client library to ping a PubSubHubbub hub
license:             ~
author:              
    - Brad Fitzpatrick <brad@danga.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP::UserAgent:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
